name: Sync Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering as well

jobs:
  format-terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: 0.48.0
      - name: Check Terragrunt version
        run: terragrunt --version
      - name: Format Terragrunt
        run: terragrunt hclfmt
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Terragrunt Formatting

  sync-files:
    runs-on: ubuntu-latest
    needs: format-terragrunt
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_BODY: "Change-type: auto sync"
          SKIP_PR: true
          PR_LABELS: |
            file-sync
            automerge